"""Revalidate the FAST tester (GPUCondIndTester) vs the R reference already
generated by hsic_validate_conditional.py. Same triples, must match 12/12."""
import os, sys
import numpy as np
_THIS = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, _THIS)
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(_THIS)), 'shared')); from paths import outdir as _outdir
OUT = _outdir('exploratory/hsic_gpu')   # was arousal_paper_overleaf/figures/2026-07-06_hsic_gpu_validation
ALPHA = 0.05

TRIPLES = [(0,1,[]),(0,4,[]),(1,2,[]),(1,2,[0]),(0,3,[]),(0,3,[1,2]),
           (2,3,[0,1]),(1,3,[0,2]),(0,3,[1,2,4]),(1,5,[3]),(0,5,[3]),(2,5,[0,3])]

def main():
    import torch
    from gpu_cits_ci_fast import GPUCondIndTester
    data = np.loadtxt(os.path.join(OUT,'cond_cases_data.csv'), delimiter=',', skiprows=1)
    rref = {}
    with open(os.path.join(OUT,'cond_r_reference.csv')) as f:
        next(f)
        for line in f:
            key, pv = line.rsplit(',',1); rref[key.strip().strip('"')] = float(pv)
    gen = torch.Generator(device='cuda'); gen.manual_seed(999)
    tester = GPUCondIndTester(data, generator=gen)
    print(f"{'i':>2}{'j':>3} {'S':<10}{'R_pval':>8}{'GPUfast':>9} {'R':>6}{'GPU':>6} {'m':>4}")
    print('-'*52); nm=0
    for (i,j,S) in TRIPLES:
        key=f"{i+1}|{j+1}|{','.join(str(s+1) for s in S) if S else ''}"
        rp=rref[key]; gp=tester.pval(i,j,S)
        rd='dep' if rp<=ALPHA else 'indep'; gd='dep' if gp<=ALPHA else 'indep'
        ok=rd==gd; nm+=ok
        print(f"{i:>2}{j:>3} {str(S):<10}{rp:8.3f}{gp:9.3f} {rd:>6}{gd:>6} {'OK' if ok else 'X':>4}")
    print('-'*52); print(f"decision agreement: {nm}/{len(TRIPLES)}")

if __name__=='__main__': main()
